### ISSUE TITLE
不能运行？

### ISSUE THREAD

**Issue by koalago** [Lucius0/egret-MatchGame#1]
你好， 我用的 engine 2.0 ，运行后XMLHttpRequest cannot load 报错。 请问如何才能运行？

操作如下：
upgrade 项目后 编译项目 调试窗口信息如下：

扫描项目列表
扫描耗时：0.319秒
执行tsc编译
tsc编译耗时：1.666秒
项目共计编译耗时：2.084秒

undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Applications/EgretEngine.app/Contents/Resources/mac/egret/tools/lib/tools/build.js:86:34
    at /Applications/EgretEngine.app/Contents/Resources/mac/egret/tools/lib/core/async.js:595:21
    at /Applications/EgretEngine.app/Contents/Resources/mac/egret/tools/lib/core/async.js:235:13
    at iterate (/Applications/EgretEngine.app/Contents/Resources/mac/egret/tools/lib/core/async.js:142:13)
    at /Applications/EgretEngine.app/Contents/Resources/mac/egret/tools/lib/core/async.js:153:25
    at /Applications/EgretEngine.app/Contents/Resources/mac/egret/tools/lib/core/async.js:237:17
    at /Applications/EgretEngine.app/Contents/Resources/mac/egret/tools/lib/core/async.js:600:34
    at /Applications/EgretEngine.app/Contents/Resources/mac/egret/tools/lib/tools/build.js:70:17
    at /Applications/EgretEngine.app/Contents/Resources/mac/egret/tools/lib/core/async.js:595:21

**Comment by Lucius0** [comment]
你好，新版本我没试过。我是在1.7.x windows下的时候写的小demo。具体问题你问下官方。这个应该是引擎的问题。
